//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorbaliBurada.Data.Entities
{

    public partial class EmlakKonutTipi:EntityBase<int>
    {
        //public int Id { get; set; }
        public string KonutTipi { get; set; }
    }
}
