//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorbaliBurada.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanIlanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IlanIlanlar()
        {
            this.IlanAdresler = new HashSet<IlanAdresler>();
            this.IlanCepheOzellikler = new HashSet<IlanCepheOzellikler>();
            this.IlanDisOzellikler = new HashSet<IlanDisOzellikler>();
            this.IlanIcOzellikler = new HashSet<IlanIcOzellikler>();
            this.IlanKimden = new HashSet<IlanKimden>();
            this.IlanKonutTipiOzellikler = new HashSet<IlanKonutTipiOzellikler>();
            this.IlanKullanimAmaci = new HashSet<IlanKullanimAmaci>();
            this.IlanlarEmlakGenel = new HashSet<IlanlarEmlakGenel>();
            this.IlanManzaraOzellikler = new HashSet<IlanManzaraOzellikler>();
            this.IlanMuhitOzellikler = new HashSet<IlanMuhitOzellikler>();
            this.IlanUlasimOzellikler = new HashSet<IlanUlasimOzellikler>();
            this.IlanYapiDurumu = new HashSet<IlanYapiDurumu>();
            this.EmlakKategoriler = new HashSet<EmlakKategoriler>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string MetreKare { get; set; }
        public Nullable<int> TakasliID { get; set; }
        public string UserName { get; set; }
    
        public virtual EmlakTakasli EmlakTakasli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanAdresler> IlanAdresler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanCepheOzellikler> IlanCepheOzellikler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanDisOzellikler> IlanDisOzellikler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanIcOzellikler> IlanIcOzellikler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanKimden> IlanKimden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanKonutTipiOzellikler> IlanKonutTipiOzellikler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanKullanimAmaci> IlanKullanimAmaci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanlarEmlakGenel> IlanlarEmlakGenel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanManzaraOzellikler> IlanManzaraOzellikler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanMuhitOzellikler> IlanMuhitOzellikler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanUlasimOzellikler> IlanUlasimOzellikler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanYapiDurumu> IlanYapiDurumu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmlakKategoriler> EmlakKategoriler { get; set; }
    }
}
