//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorbaliBurada.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanlarEmlakGenel
    {
        public int IlanEmlakGenelID { get; set; }
        public Nullable<int> EmlakIlanID { get; set; }
        public Nullable<int> OdaSayisiID { get; set; }
        public Nullable<int> BinaYasiID { get; set; }
        public Nullable<int> BulunduguKatID { get; set; }
        public Nullable<int> KatSayisiID { get; set; }
        public Nullable<int> IsitmaID { get; set; }
        public Nullable<int> BanyoSayisiID { get; set; }
        public Nullable<int> KullanimDurumuID { get; set; }
        public Nullable<int> SiteIcerisindeID { get; set; }
        public Nullable<bool> Aidat { get; set; }
    
        public virtual EmlakBanyoSayisi EmlakBanyoSayisi { get; set; }
        public virtual EmlakBinaYasi EmlakBinaYasi { get; set; }
        public virtual EmlakBulunduguKat EmlakBulunduguKat { get; set; }
        public virtual EmlakIsitmaTuru EmlakIsitmaTuru { get; set; }
        public virtual EmlakKatSayisi EmlakKatSayisi { get; set; }
        public virtual EmlakKullanimDurumu EmlakKullanimDurumu { get; set; }
        public virtual EmlakOdaSayisi EmlakOdaSayisi { get; set; }
        public virtual EmlakSiteIcerisinde EmlakSiteIcerisinde { get; set; }
        public virtual IlanIlanlar IlanIlanlar { get; set; }
    }
}
