//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorbaliBurada.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategoriler()
        {
            this.Konular = new HashSet<Konular>();
        }
    
        public int Id { get; set; }
        public string KategoriAd { get; set; }
        public string Aciklama { get; set; }
        public string Seo { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string Statu { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konular> Konular { get; set; }
    }
}
