//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorbaliBurada.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Konular()
        {
            this.Dosyalar = new HashSet<Dosyalar>();
            this.Etiketler = new HashSet<Etiketler>();
            this.Resimler = new HashSet<Resimler>();
            this.Kategoriler = new HashSet<Kategoriler>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string KisaIcerik { get; set; }
        public string UzunIcerik { get; set; }
        public string Resim { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Statu { get; set; }
        public Nullable<int> OkunmaSayisi { get; set; }
        public Nullable<int> YorumSayisi { get; set; }
        public string Dosya { get; set; }
        public Nullable<int> Manset { get; set; }
        public string Seo { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dosyalar> Dosyalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiketler> Etiketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resimler> Resimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategoriler> Kategoriler { get; set; }
    }
}
