//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorbaliBurada.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sidart_torbaliBuradaEntities : DbContext
    {
        public sidart_torbaliBuradaEntities()
            : base("name=sidart_torbaliBuradaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArsaGenelOzelikleri> ArsaGenelOzelikleri { get; set; }
        public virtual DbSet<ArsaKonumu> ArsaKonumu { get; set; }
        public virtual DbSet<ArsaManzara> ArsaManzara { get; set; }
        public virtual DbSet<Bulten> Bulten { get; set; }
        public virtual DbSet<Dosyalar> Dosyalar { get; set; }
        public virtual DbSet<EmlakAltyapi> EmlakAltyapi { get; set; }
        public virtual DbSet<EmlakBanyoSayisi> EmlakBanyoSayisi { get; set; }
        public virtual DbSet<EmlakBinaYasi> EmlakBinaYasi { get; set; }
        public virtual DbSet<EmlakBulunduguKat> EmlakBulunduguKat { get; set; }
        public virtual DbSet<EmlakCephe> EmlakCephe { get; set; }
        public virtual DbSet<EmlakDetayBilgisi> EmlakDetayBilgisi { get; set; }
        public virtual DbSet<EmlakDisOzellikler> EmlakDisOzellikler { get; set; }
        public virtual DbSet<EmlakGenelOzellikler> EmlakGenelOzellikler { get; set; }
        public virtual DbSet<EmlakIcOzellikler> EmlakIcOzellikler { get; set; }
        public virtual DbSet<EmlakIlanTipi> EmlakIlanTipi { get; set; }
        public virtual DbSet<EmlakImarDurumu> EmlakImarDurumu { get; set; }
        public virtual DbSet<EmlakIsitmaTuru> EmlakIsitmaTuru { get; set; }
        public virtual DbSet<EmlakKategoriler> EmlakKategoriler { get; set; }
        public virtual DbSet<EmlakKatSayisi> EmlakKatSayisi { get; set; }
        public virtual DbSet<EmlakKimden> EmlakKimden { get; set; }
        public virtual DbSet<EmlakKonutTipi> EmlakKonutTipi { get; set; }
        public virtual DbSet<EmlakKullanimAmaci> EmlakKullanimAmaci { get; set; }
        public virtual DbSet<EmlakKullanimDurumu> EmlakKullanimDurumu { get; set; }
        public virtual DbSet<EmlakLocation> EmlakLocation { get; set; }
        public virtual DbSet<EmlakManzara> EmlakManzara { get; set; }
        public virtual DbSet<EmlakMuhit> EmlakMuhit { get; set; }
        public virtual DbSet<EmlakOdaSayisi> EmlakOdaSayisi { get; set; }
        public virtual DbSet<EmlakSiteIcerisinde> EmlakSiteIcerisinde { get; set; }
        public virtual DbSet<EmlakTakasli> EmlakTakasli { get; set; }
        public virtual DbSet<EmlakTapuDurumu> EmlakTapuDurumu { get; set; }
        public virtual DbSet<EmlakUlasim> EmlakUlasim { get; set; }
        public virtual DbSet<EmlakYapiDurumu> EmlakYapiDurumu { get; set; }
        public virtual DbSet<EmlakYapiTipi> EmlakYapiTipi { get; set; }
        public virtual DbSet<Etiketler> Etiketler { get; set; }
        public virtual DbSet<IlanAdresler> IlanAdresler { get; set; }
        public virtual DbSet<IlanCepheOzellikler> IlanCepheOzellikler { get; set; }
        public virtual DbSet<IlanDisOzellikler> IlanDisOzellikler { get; set; }
        public virtual DbSet<IlanIcOzellikler> IlanIcOzellikler { get; set; }
        public virtual DbSet<IlanIlanlar> IlanIlanlar { get; set; }
        public virtual DbSet<IlanKimden> IlanKimden { get; set; }
        public virtual DbSet<IlanKonutTipiOzellikler> IlanKonutTipiOzellikler { get; set; }
        public virtual DbSet<IlanKullanimAmaci> IlanKullanimAmaci { get; set; }
        public virtual DbSet<IlanlarEmlakGenel> IlanlarEmlakGenel { get; set; }
        public virtual DbSet<IlanManzaraOzellikler> IlanManzaraOzellikler { get; set; }
        public virtual DbSet<IlanMuhitOzellikler> IlanMuhitOzellikler { get; set; }
        public virtual DbSet<IlanUlasimOzellikler> IlanUlasimOzellikler { get; set; }
        public virtual DbSet<IlanYapiDurumu> IlanYapiDurumu { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Konular> Konular { get; set; }
        public virtual DbSet<Resimler> Resimler { get; set; }
        public virtual DbSet<ZiyaretciUrl> ZiyaretciUrl { get; set; }
    }
}
