//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorbaliBurada.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZiyaretciUrl
    {
        public int Id { get; set; }
        public string Ip { get; set; }
        public string RefererUrl { get; set; }
        public string GetUrl { get; set; }
        public string Browser { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
